name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Verify Python Version
        run: |
          uv run python -c "import sys; print(f'Python version: {sys.version}')"
          uv run python -c "import sys; assert sys.version_info >= (3, 10), f'Python version {sys.version} is less than 3.10'"
      - name: Install Dependencies
        run: uv sync --all-extras
      - name: Install Project Dependencies
        run: uv run pip install -r requirements.txt
      - name: Test
        run: uv run pytest tests/ --cov=pydantic_client --cov-report=term-missing:skip-covered --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
            token: ${{ secrets.CODECOV_TOKEN }}

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
