name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 明确指定3.10或更高版本，与项目要求一致
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -c "import sys; print(f'Python version: {sys.version}')"
        python -c "import sys; assert sys.version_info >= (3, 10), f'Python version {sys.version} is less than 3.10'"
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
